Parameters:
  Environment:
    Type: String
    Description: The environment for the resources (e.g., dev, prod)
    Default: staging  
  Project:
    Type: String
    Description: The project name (e.g., MyProject)
  VpcCIDR:
    Type: String
    Description: CIDR block for the VPC    
  InstanceType:
     Type: String
     Description: Type of EC2 Insatance
     Default: t2.micro  


Resources:
  EC2InstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service: "ec2.amazonaws.com"
      Policies:
        - PolicyName: "SSMPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ssm:DescribeInstanceInformation"
                  - "ssm:GetAutomationExecution"
                  - "ssm:ListCommands"
                  - "ssm:SendCommand"
                  - "ssm:CancelCommand"
                  - "ssm:ListCommandInvocations"
                  - "ssm:DescribeDocument"
                  - "ssm:GetCommandInvocation"
                Resource: "*"

  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro  
      ImageId: ami-xxxxxxxx  
      KeyName: !Ref KeyName   
      SecurityGroupIds:
        - !Sub Fn::ImportValue MySecurityGroupId  
      SubnetId: !Sub Fn::ImportValue MyPublicSubnetId1  
      IamInstanceProfile: 
        Ref: EC2InstanceRole  
      Tags:
        - Key: "Name"
          Value: !Sub "${Environment}-${Project}-EC2Instance"
        - Key: "Environment"
          Value: !Ref Environment
        - Key: "Project"
          Value: !Ref Project

Outputs:
  EC2InstanceId:
    Description: "EC2 Instance ID"
    Value: !Ref MyEC2Instance

  EC2InstancePublicIp:
    Description: "Public IP of the EC2 instance"
    Value: !GetAtt MyEC2Instance.PublicIp
